<?php exit; ?>
2$$$
3$$$
4$$$
14$ $ $
6$$$
15$ $ $
8$$$
16$ $ $
10$$$
12$$$
5$$$
7$$$
11$$$
9$$$
13$&nbsp;$<br />|n|Witamy w sklepie internetowym Pracowni Pedagogicznej i Wydawniczej.|n|<br /><br />|n|Przypominamy:<br />|n|Dystrybucj± naszych ksi±¿ek zajmuje siê równie¿ wydawnictwo <a style="font-size: 12px;font-weight: bold;color: #666666;background: url('../../_images/layout/pictograms/anchor.gif') 0px 50% no-repeat;" href="http://www.mac.pl/">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>MAC EDUKACJA</b></a>.|n|<br /><br />|n|Przy sk³adaniu zamówienia w naszym sklepie istnieje mo¿liwo¶æ okre¶lenia terminu realizacji zamówienia.<br /><br />|n|Jedyna forma p³atno¶ci za zrealizowane zamówienie to p³atno¶æ przy odbiorze przesy³ki.<br /><br />|n|Do kwoty zamówienia do 200 z³ doliczamy koszty wysy³ki wg taryfy poczty lub kuriera.|n|<br /><br />|n|Nasze dane teleadresowe znale¼æ mo¿na w dziale: <a style="font-size: 12px;font-weight: bold;color: #666666;background: url('../../_images/layout/pictograms/anchor.gif') 0px 50% no-repeat;" href="index.php?p=p_1&sName=kontakt">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>kontakt</b></a>.|n|<br /><br />|n|W zwi±zku z Ustaw± z dnia 29 sierpnia 1997 r. o ochronie danych osobowych (DzU z 2002 r. Nr 101, poz. 926 z pó¼n. zm.) osoby dokonuj±ce zakupów w naszym sklepie internetowym prosimy o przes³anie wype³nionego i podpisanego <a style="font-size: 12px;font-weight: bold;color: #666666;background: url('../../_images/layout/pictograms/download.gif') 0px 50% no-repeat;" href="../../download/oswiadczenie_dane.pdf" target="_top" onMouseOver="self.status='Pobierz o¶wiadczenie'; return true;" title="Plik do pobrania (rozmiar pliku: 57,4 kB)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>o¶wiadczenia</b></a> dotycz±cego przetwarzania danych osobowych.|n|<br />|n|Odes³anie <a style="font-size: 12px;font-weight: bold;color: #666666;background: url('../../_images/layout/pictograms/download.gif') 0px 50% no-repeat;" href="../../download/oswiadczenie_dane.pdf" target="_top" onMouseOver="self.status='Pobierz o¶wiadczenie'; return true;" title="Plik do pobrania (rozmiar pliku: 57,4 kB)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>o¶wiadczenia</b></a> bêdziemy traktowaæ jako wyra¿enie zgody na przetwarzanie danych osobowych w rozumieniu ww. Ustawy. Jednocze¶nie informujemy, ¿e w przypadku niewype³nienia o¶wiadczenia lub nieudzielenia zgody na przetwarzanie danych osobowych, dane osobowe nie zostan± wprowadzone do bazy Pracowni Pedagogicznej i Wydawniczej.$
1$$<!--Je¶li masz pytania dotycz±ce oferowanych produktów, mo¿esz siê z nami skontaktowaæ, korzystaj±c z <a style="font-size: 12px;font-weight: bold;color: #666666;background: url(../../_images/layout/pictograms/download.gif) 0px 50% no-repeat;" href="../../download/formularz_2006.pdf" target="_top" onMouseOver="self.status='Pobierz formularz zamówienia'; return true;" title="Plik do pobrania (rozmiar pliku: 169 kB)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;formularza zamówienia</a>.|n|<br /><br />--><br />|n|Pracownia Pedagogiczna i Wydawnicza<br />Janina Korzañska<br />|n|ul. Lucerny 80-82<br />|n|04-687 Warszawa Anin|n|<br /><br />|n|tel. (0) 22 815 27 89<br />|n|tel./faks (0) 22 851 50 83<br />|n|<script> var l_01="sp"; var l_02="rz"; var l_03="eda"; var l_04="z"; var d_01="pp"; var d_02="iw"; var d_03="co"; var d_04="m.p"; var d_05="l";</script>|n|e-mail: <script> document.write("<a style='font-size: 12px;font-weight: bold;color: #666666;background: url(../../_images/layout/pictograms/envelope.gif) 0px 50% no-repeat;' href='ma"+"ilto:"+l_01+l_02+l_03+l_04+"@"+d_01+d_02+"."+d_03+d_04+d_05+"'>     <b>"+l_01+l_02+l_03+l_04+"@"+d_01+d_02+"."+d_03+d_04+d_05+"</b></a>"); </script>$
