<?php exit; ?>
89$&nbsp;$
96$&nbsp;$
5$ &nbsp;$
6$&nbsp;$
7$&nbsp;$
17$&nbsp;$
18$&nbsp;$
19$&nbsp;$
20$&nbsp;$
2$Umo¿liwia monitorowanie pracy nauczyciela i rozwój umiejêtno¶ci uczniów. Numer dopuszczenia: DKW&#8211;4014&#8211;18/9.$
4$Poradnik zawiera zestaw umiejêtno¶ci uporz±dkowanych wed³ug kategorii przyjêtych w programie nauczania (mówienie i s³uchanie, czytanie, pisanie, stosowanie wiedzy i umiejêtno¶ci, rozwi±zywanie problemów, dzia³ania i prze¿ycia artystyczne, relacje z rówie¶nikami i doros³ymi, aktywno¶æ s³u¿±ca rozwojowi fizycznemu) i praktyczne wskazówki do opisywania osi±gniêæ ucznia. U³atwia nauczycielowi u³o¿enie indywidualnego arkusza obserwacyjnego ucznia i zredagowanie oceny opisowej &#8211; dostêpny w formie broszury i na dyskietce.$
10$Praca zbiorowa pracowników naukowych i studentów UAM w Poznaniu pod redakcj± dr Renaty Michalak. Atrakcyjne scenariusze zajêæ przyrodniczych to propozycje ukazuj±ce, jak mo¿na na etapie nauczania pocz±tkowego przygotowaæ dzieci do naukowego badania zjawisk fizycznych, a w konsekwencji rozumienia otaczaj±cej rzeczywisto¶ci.$
11$Praca zbiorowa pracowników naukowych i studentów UAM w Poznaniu pod redakcj± dr Renaty Michalak. Atrakcyjne scenariusze zajêæ przyrodniczych to propozycje ukazuj±ce, jak mo¿na na etapie nauczania pocz±tkowego przygotowaæ dzieci do naukowego badania zjawisk fizycznych, a w konsekwencji rozumienia otaczaj±cej rzeczywisto¶ci.$
12$Praca zbiorowa pracowników naukowych i studentów UAM w Poznaniu pod redakcj± dr Renaty Michalak. Atrakcyjne scenariusze zajêæ przyrodniczych to propozycje ukazuj±ce, jak mo¿na na etapie nauczania pocz±tkowego przygotowaæ dzieci do naukowego badania zjawisk fizycznych, a w konsekwencji rozumienia otaczaj±cej rzeczywisto¶ci.$
13$Opracowana zgodnie z ide± nauczania zintegrowanego propozycja zabaw, gier i æwiczeñ ruchowych zwi±zanych tematycznie z tre¶ciami kszta³cenia zawartymi w Programie abc. Pozwala wykorzystywaæ w zajêciach zintegrowanych:|n|<ul>|n|<li>æwiczenia kszta³tuj±ce, ogólnorozwojowe i korekcyjne prowadzone w formie zabawowej jako sta³y element lekcji</li>|n|<li>znane i zapomniane gry podwórkowe</li>|n|<li>oryginalne zabawy z elementami fantastycznymi i ba¶niowymi.</li>|n|</ul>$
15$Broszura skierowana do rodziców. Informuje, z jakimi problemami mog± zetkn±æ siê rodzice dzieci w klasach 1&#8211;3. Dostarcza informacji, które zaciekawi±, zastanowi± i zachêc± do udzia³u w ¿yciu szkolnym. Zwraca uwagê na rozumienie istoty programu zintegrowanego, systemu oceniania opisowego i potrzebê wspó³pracy rodziców i nauczycieli.$
16$Broszura skierowana do rodziców. Informuje, z jakimi problemami mog± zetkn±æ siê rodzice dzieci w klasach 1&#8211;3. Dostarcza informacji, które zaciekawi±, zastanowi± i zachêc± do udzia³u w ¿yciu szkolnym. Zwraca uwagê na rozumienie istoty programu zintegrowanego, systemu oceniania opisowego i potrzebê wspó³pracy rodziców i nauczycieli.$
8$Oryginalne pomys³y nauczycieli praktyków na zorganizowanie ca³odziennych zajêæ:|n|<ul>|n|<li>pozwalaj± nauczycielowi skróciæ czas potrzebny na przygotowanie zajêæ</li>|n|<li>zawieraj± wskazówki, jak dostosowaæ propozycje do potrzeb i mo¿liwo¶ci dzieci</li>|n|<li>nie ograniczaj± indywidualnej aktywno¶ci uczniów oraz pomys³owo¶ci nauczyciela.</li>|n|</ul>$
9$Oryginalne pomys³y nauczycieli praktyków na zorganizowanie ca³odziennych zajêæ:|n|<ul>|n|<li>pozwalaj± nauczycielowi skróciæ czas potrzebny na przygotowanie zajêæ</li>|n|<li>zawieraj± wskazówki, jak dostosowaæ propozycje do potrzeb i mo¿liwo¶ci dzieci</li>|n|<li>nie ograniczaj± indywidualnej aktywno¶ci uczniów oraz pomys³owo¶ci nauczyciela.</li>|n|</ul>$
82$Unikatowa publikacja o charakterze interaktywnym dla dzieci w wieku 6&#8211;12 lat. Dostosowana tematycznie do pakietów podrêcznikowych. Bogato ilustrowana. £±czy walory leksykonu, albumu, ksi±¿eczki do kolorowania i wycinania oraz zestawu gier i æwiczeñ edukacyjnych.|n|<br /><br />|n|Notki encyklopedyczne do ilustracji znajduj±cych siê we wszystkich czê¶ciach albumu, do³±czone jako dyskietka do 1. jego czê¶ci, mo¿na <a style="font-size: 12px;font-weight: bold;color: #666666;background: url(../../_images/layout/pictograms/download.gif) 0px 50% no-repeat;" href="../../download/encyklopedia_zip.exe" target="_top" onMouseOver="self.status='Pobierz program komputerowy'; return true;" title="Program do pobrania (rozmiar pliku: 561 kB)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pobraæ</a> w formie programu komputerowego.$
83$Unikatowa publikacja o charakterze interaktywnym dla dzieci w wieku 6&#8211;12 lat. Dostosowana tematycznie do pakietów podrêcznikowych. Bogato ilustrowana. £±czy walory leksykonu, albumu, ksi±¿eczki do kolorowania i wycinania oraz zestawu gier i æwiczeñ edukacyjnych.$
84$Unikatowa publikacja o charakterze interaktywnym dla dzieci w wieku 6&#8211;12 lat. Dostosowana tematycznie do pakietów podrêcznikowych. Bogato ilustrowana. £±czy walory leksykonu, albumu, ksi±¿eczki do kolorowania i wycinania oraz zestawu gier i æwiczeñ edukacyjnych.$
88$Nowatorski zestaw map i foliogramów do samodzielnego wykonywania map Polski, Europy i ¶wiata (fizycznych, historycznych, przyrodniczych). Odwo³uje siê do potrzeby spontanicznej aktywno¶ci dziecka i w naturalny sposób j± wyzwala. Pozwala nauczycielowi w przystêpny i atrakcyjny sposób wprowadziæ ucznia w obszary wiedzy geograficznej i historycznej.$
90$Zestaw atrakcyjnych zadañ, gier i zabaw logicznych nawi±zuj±cych do tre¶ci i tematyki objêtej Programem abc. Sk³aniaj± dziecko do samodzielnego wyboru i indywidualnej aktywno¶ci.$
91$Zestaw atrakcyjnych zadañ, gier i zabaw logicznych nawi±zuj±cych do tre¶ci i tematyki objêtej Programem abc. Sk³aniaj± dziecko do samodzielnego wyboru i indywidualnej aktywno¶ci.$
92$Zestaw atrakcyjnych zadañ, gier i zabaw logicznych nawi±zuj±cych do tre¶ci i tematyki objêtej Programem abc. Sk³aniaj± dziecko do samodzielnego wyboru i indywidualnej aktywno¶ci.$
14$Zestaw 32 kolorowych ilustracji do tekstów literackich zawartych w pakiecie Moje abc dla klasy III i zbiorach tekstów Opowiadania i wiersze wraz z przewodnikiem dla nauczyciela. Tekst literacki zosta³ potraktowany jako inspiracja do ró¿norodnych æwiczeñ, dziêki którym dziecko bêdzie mog³o poznaæ jego kompozycjê, nastrój, poszukiwaæ narratora, okre¶laæ postawy bohaterów.|n|<br /><br />|n|Przewodnik mo¿na <a style="font-size: 12px;font-weight: bold;color: #666666;background: url(../../_images/layout/pictograms/download.gif) 0px 50% no-repeat;" href="../../download/przewodnik_mio.doc" target="_top" onMouseOver="self.status='Pobierz plik'; return true;" title="Plik do pobrania (rozmiar pliku: 81 kB)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pobraæ</a> w formie pliku tekstowego.$
93$Powie¶æ dla dzieci o losach Franka i jego sympatycznych przyjació³ zwanych abecelkami. Pe³en humoru opis ich szkolnych perypetii splata siê z tajemnic± Bursztynowego Domu i mieszkaj±cego w nim ducha. Lekturê uprzyjemniaj± zabawne ilustracje autorstwa Joanny Olech.|n|<br /><br />|n|Abecelki to publikacja uhonorowana w 2004 r. Nagrod± Literack± im. Kornela Makuszyñskiego.$
94$Kontynuacja powie¶ci dla dzieci o losach Franka i jego sympatycznych przyjació³ zwanych abecelkami. Pe³en humoru opis ich szkolnych perypetii splata siê z tajemnic± Bursztynowego Domu i mieszkaj±cego w nim ducha. Lekturê uprzyjemniaj± zabawne ilustracje autorstwa Joanny Olech.$
39$Pierwsza czê¶æ atrakcyjnego zestawu zadañ edukacyjnych i tematycznie zwi±zanych z nimi tekstów. Karty dla uczniów klasy I sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, proponuj± zadania wyzwalaj±ce spontaniczno¶æ i chêæ dzia³ania, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
58$Pierwsza czê¶æ atrakcyjnego zestawu zadañ edukacyjnych i tematycznie zwi±zanych z nimi tekstów. Karty dla uczniów klasy II sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, proponuj± zadania wyzwalaj±ce spontaniczno¶æ i chêæ dzia³ania, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
76$Pierwsza czê¶æ atrakcyjnego zestawu zadañ edukacyjnych i tematycznie zwi±zanych z nimi tekstów. Karty dla uczniów klasy III sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, proponuj± zadania wyzwalaj±ce spontaniczno¶æ i chêæ dzia³ania, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
21$Atrakcyjny zestaw zabawnych zadañ edukacyjnych i krótkich tekstów, sprzyjaj±cych indywidualizacji pracy z dzieckiem, wyzwalaj±cych spontaniczno¶æ, zachêcaj±cych do podejmowania twórczych dzia³añ i zabawy.|n|<ul>|n|<li>rozwija umiejêtno¶ci niezbêdne do podjêcia nauki</li>|n|<li>odwo³uje siê do do¶wiadczeñ dziecka, umiejêtnie ³±cz±c zabawê z procesem uczenia siê</li>|n|<li>pobudza naturaln± aktywno¶æ, rozwijaj±c wyobra¼niê i zainteresowania.</li>|n|</ul>$
40$Druga czê¶æ atrakcyjnego zestawu zadañ edukacyjnych i tematycznie zwi±zanych z nimi tekstów. Karty dla uczniów klasy I sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, proponuj± zadania wyzwalaj±ce spontaniczno¶æ i chêæ dzia³ania, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
59$Druga czê¶æ atrakcyjnego zestawu zadañ edukacyjnych i tematycznie zwi±zanych z nimi tekstów. Karty dla uczniów klasy II sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, proponuj± zadania wyzwalaj±ce spontaniczno¶æ i chêæ dzia³ania, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
77$Druga czê¶æ atrakcyjnego zestawu zadañ edukacyjnych i tematycznie zwi±zanych z nimi tekstów. Karty dla uczniów klasy III sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, proponuj± zadania wyzwalaj±ce spontaniczno¶æ i chêæ dzia³ania, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
22$Atrakcyjny zestaw zabawnych zadañ edukacyjnych i krótkich tekstów, sprzyjaj±cych indywidualizacji pracy z dzieckiem, wyzwalaj±cych spontaniczno¶æ, zachêcaj±cych do podejmowania twórczych dzia³añ i zabawy.|n|<ul>|n|<li>rozwija umiejêtno¶ci niezbêdne do podjêcia nauki</li>|n|<li>odwo³uje siê do do¶wiadczeñ dziecka, umiejêtnie ³±cz±c zabawê z procesem uczenia siê</li>|n|<li>pobudza naturaln± aktywno¶æ, rozwijaj±c wyobra¼niê i zainteresowania.</li>|n|</ul>$
78$Pierwszy zbiór tekstów dla klasy III, zwi±zany tematycznie z kartami pracy. Teksty pozwalaj± na dostosowanie nauki czytania do indywidualnych mo¿liwo¶ci i potrzeb dziecka, rozbudzaj± ciekawo¶æ i zainteresowania literackie.$
60$Pierwszy zbiór tekstów dla klasy II, zwi±zany tematycznie z kartami pracy. Teksty pozwalaj± na dostosowanie nauki czytania do indywidualnych mo¿liwo¶ci i potrzeb dziecka, rozbudzaj± ciekawo¶æ i zainteresowania literackie.$
41$Pierwsza czê¶æ zeszytu przygotowanego z my¶l± o pracach domowych najm³odszych uczniów. Powi±zany jest tematycznie z materia³em omawianym ka¿dego dnia w szkole. Zawarte w zeszytach æwiczenia umo¿liwiaj± rozwijanie twórczo¶ci, doskonalenie czytania ze zrozumieniem, æwiczenie pisania.$
79$Drugi zbiór tekstów dla klasy III, zwi±zany tematycznie z kartami pracy. Teksty pozwalaj± na dostosowanie nauki czytania do indywidualnych mo¿liwo¶ci i potrzeb dziecka, rozbudzaj± ciekawo¶æ i zainteresowania literackie.$
61$Drugi zbiór tekstów dla klasy II, zwi±zany tematycznie z kartami pracy. Teksty pozwalaj± na dostosowanie nauki czytania do indywidualnych mo¿liwo¶ci i potrzeb dziecka, rozbudzaj± ciekawo¶æ i zainteresowania literackie.$
42$Druga czê¶æ zeszytu przygotowanego z my¶l± o pracach domowych najm³odszych uczniów. Powi±zany jest tematycznie z materia³em omawianym ka¿dego dnia w szkole. Zawarte w zeszytach æwiczenia umo¿liwiaj± rozwijanie twórczo¶ci, doskonalenie czytania ze zrozumieniem, æwiczenie pisania.$
85$ $
43$Pierwszy zbiór tekstów dla klasy I, zwi±zany tematycznie z kartami pracy. Teksty pozwalaj± na dostosowanie nauki czytania do indywidualnych mo¿liwo¶ci i potrzeb dziecka, rozbudzaj± ciekawo¶æ i zainteresowania literackie.$
25$Atrakcyjny zestaw zabawnych zadañ edukacyjnych i krótkich tekstów, sprzyjaj±cych indywidualizacji pracy dziecka, wyzwalaj±cych spontaniczno¶æ, zachêcaj±cych do podejmowania twórczych dzia³añ i zabawy.$
62$Zawiera tre¶ci kszta³cenia uporz±dkowane w o¶rodkach tematycznych, z podzia³em na dni pracy oraz ciekawe propozycje dzia³añ edukacyjnych. Wskazuje ¶rodki dydaktyczne potrzebne danego dnia. Proponuje te¿ ró¿ne formy aktywno¶ci ucznia. Znajduje siê tu równie¿ spis umiejêtno¶ci, u³atwiaj±cy przeprowadzenie bilansu osi±gniêæ ucznia przez kilka kolejnych dni i szczegó³owe opisy konkretnych rozwi±zañ metodycznych, a tak¿e zapisy w dzienniku.$
80$Zawiera tre¶ci kszta³cenia uporz±dkowane w o¶rodkach tematycznych, z podzia³em na dni pracy oraz ciekawe propozycje dzia³añ edukacyjnych. Wskazuje ¶rodki dydaktyczne potrzebne danego dnia. Proponuje te¿ ró¿ne formy aktywno¶ci ucznia. Znajduje siê tu równie¿ spis umiejêtno¶ci, u³atwiaj±cy przeprowadzenie bilansu osi±gniêæ ucznia przez kilka kolejnych dni i szczegó³owe opisy konkretnych rozwi±zañ metodycznych, a tak¿e zapisy w dzienniku.$
86$ $
81$ $
63$ $
26$Atrakcyjny zestaw zabawnych zadañ edukacyjnych i krótkich tekstów, sprzyjaj±cych indywidualizacji pracy dziecka, wyzwalaj±cych spontaniczno¶æ, zachêcaj±cych do podejmowania twórczych dzia³añ i zabawy.$
44$Drugi zbiór tekstów dla klasy I, zwi±zany tematycznie z kartami pracy. Teksty pozwalaj± na dostosowanie nauki czytania do indywidualnych mo¿liwo¶ci i potrzeb dziecka, rozbudzaj± ciekawo¶æ i zainteresowania literackie.$
87$ $
45$Trzeci zbiór tekstów dla klasy I, zwi±zany tematycznie z kartami pracy. Teksty pozwalaj± na dostosowanie nauki czytania do indywidualnych mo¿liwo¶ci i potrzeb dziecka, rozbudzaj± ciekawo¶æ i zainteresowania literackie.$
36$Przewodnik dla nauczyciela zawiera tre¶ci kszta³cenia uporz±dkowane w blokach tematycznych, z podzia³em na dni pracy oraz ciekawe propozycje dzia³añ edukacyjnych. Wskazuje ¶rodki dydaktyczne potrzebne danego dnia. Proponuje ró¿ne formy aktywno¶ci ucznia. Zawiera spis umiejêtno¶ci, u³atwiaj±cy przeprowadzenie bilansu osi±gniêæ ucznia, szczegó³owe opisy konkretnych rozwi±zañ metodycznych, a tak¿e zapisy w dzienniku.|n|<br /><br />|n|Przewodnik dla nauczyciela posiada nowatorsk± szatê graficzn± &#8211; pierwsz± tak± na polskim rynku.$
27$Nowatorski program ukierunkowuj±cy i precyzuj±cy, w jaki sposób realizowaæ najnowsze tendencje w edukacji ma³ych dzieci. Prezentowane rozwi±zania ucz±, jak wykorzystywaæ wiedzê w codziennym ¿yciu i przewiduj± indywidualizacjê pracy dzieci. G³ównym celem programu jest nauka poprzez zabawê, twórczo¶æ i poszukiwania. Przewodniki zawieraj± propozycje dzia³añ stanowi±cych podstawê planowania codziennej pracy. Wiêkszo¶æ zaproponowanych pomys³ów zosta³a sprawdzona w praktyce.$
28$Ilustrowane wyrazy do nauki czytania dla dzieci w wieku 5&#8211;6 lat &#8211; w formacie A4:|n|<br /><br />|n|<ul>|n|<li>124 plansze z wyrazami do czytania globalnego</li>|n|<li>30 kart przedstawiaj±cych wzory liter pisanych oraz ilustruj±cych wyrazy podstawowe, które wspomagaj± naukê czytania.</li>|n|</ul>$
46$Zawiera tre¶ci kszta³cenia uporz±dkowane w o¶rodkach tematycznych, z podzia³em na dni pracy oraz ciekawe propozycje dzia³añ edukacyjnych. Wskazuje ¶rodki dydaktyczne potrzebne danego dnia. Proponuje te¿ ró¿ne formy aktywno¶ci ucznia. Znajduje siê tu równie¿ spis umiejêtno¶ci, u³atwiaj±cy przeprowadzenie bilansu osi±gniêæ ucznia przez kilka kolejnych dni i szczegó³owe opisy konkretnych rozwi±zañ metodycznych, a tak¿e zapisy w dzienniku.$
37$Przewodnik dla nauczyciela zawiera tre¶ci kszta³cenia uporz±dkowane w blokach tematycznych, z podzia³em na dni pracy oraz ciekawe propozycje dzia³añ edukacyjnych. Wskazuje ¶rodki dydaktyczne potrzebne danego dnia. Proponuje ró¿ne formy aktywno¶ci ucznia. Zawiera spis umiejêtno¶ci, u³atwiaj±cy przeprowadzenie bilansu osi±gniêæ ucznia, szczegó³owe opisy konkretnych rozwi±zañ metodycznych, a tak¿e zapisy w dzienniku.|n|<br /><br />|n|Przewodnik dla nauczyciela posiada nowatorsk± szatê graficzn± &#8211; pierwsz± tak± na polskim rynku.$
29$Zestaw ilustracji wielotematycznych dla dzieci w wieku 3&#8211;6 lat.|n|<br /><br /><br /><br /><br />|n|<ul>|n|<li>10 plansz formatu A4 z kolorowymi ilustracjami do tekstów literackich zawartych w przewodnikach dla nauczycieli do klasy 0</li>|n|<li>10 plansz formatu A4 z kolorow± prezentacj± tematyki o¶rodka</li>|n|<li>6 plansz formatu A3 z ilustracjami pór roku.</li>|n|</ul>$
56$Przewodnik dla nauczyciela zawiera tre¶ci kszta³cenia uporz±dkowane w blokach tematycznych, z podzia³em na dni pracy oraz ciekawe propozycje dzia³añ edukacyjnych. Wskazuje ¶rodki dydaktyczne potrzebne danego dnia. Proponuje ró¿ne formy aktywno¶ci ucznia. Zawiera spis umiejêtno¶ci, u³atwiaj±cy przeprowadzenie bilansu osi±gniêæ ucznia, szczegó³owe opisy konkretnych rozwi±zañ metodycznych, a tak¿e zapisy w dzienniku.$
47$ $
57$Przewodnik dla nauczyciela zawiera tre¶ci kszta³cenia uporz±dkowane w blokach tematycznych, z podzia³em na dni pracy oraz ciekawe propozycje dzia³añ edukacyjnych. Wskazuje ¶rodki dydaktyczne potrzebne danego dnia. Proponuje ró¿ne formy aktywno¶ci ucznia. Zawiera spis umiejêtno¶ci, u³atwiaj±cy przeprowadzenie bilansu osi±gniêæ ucznia, szczegó³owe opisy konkretnych rozwi±zañ metodycznych, a tak¿e zapisy w dzienniku.$
1$Program kszta³cenia zintegrowanego abc &#8211; I etap edukacji &#8211; Janiny Korzañskiej (nr dopuszczenia: DKW&#8211;4014&#8211;18/99) powsta³ we wspó³pracy z nauczycielk± nauczania pocz±tkowego Renat± Mreñc± oraz pracownikiem naukowym Wydzia³u Pedagogicznego UW dr Ma³gorzat± ¯ytko. Program odpowiada wspó³czesnym tendencjom edukacyjnym, umo¿liwia szkole realizacjê zadañ wynikaj±cych z reformy o¶wiaty, zaspokaja potrzebê zdobywania przez uczniów umiejêtno¶ci i kompetencji w sposób samodzielny i kompleksowy.|n|<ul>|n|<li>przygotowuje do samodzielnego rozwi±zywania problemów</li>|n|<li>kszta³tuje postawê badawcz± dziecka</li>|n|<li>uczy aktywnego poszukiwania informacji</li>|n|<li>przekazuje wzory skutecznego porozumiewania siê w ró¿nych sytuacjach</li>|n|<li>zachêca do podejmowania dzia³añ i organizowania wspó³pracy z innymi lud¼mi</li>|n|<li>sk³ania do stosowania w praktyce zdobytych umiejêtno¶ci i posiadanej wiedzy.</li>|n|</ul>$
31$Karty pracy stanowi± ciekaw± propozycjê zró¿nicowanych pod wzglêdem formy zadañ edukacyjnych dotycz±cych czytania, pisania, liczenia, wycinania, sklejania itd. Sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
32$Wiêkszo¶æ zadañ w Æwiczeniach jest przeznaczona do pracy samodzielnej. Pozwalaj± na daleko id±c± indywidualizacjê pracy, umo¿liwiaj± uczniom decydowanie o wyborze rodzaju aktywno¶ci zale¿nie od interpretacji zadania, sposobu rozwi±zania, potrzebnych materia³ów i narzêdzi.$
98$Autorka i wydawca: Ma³gorzata Sroka, Bydgoszcz 2007.<br /><br />|n|&#8222;Matematyczne podró¿e Kropki i Plusika&#8221; adresowane s± do dzieci przygotowuj±cych siê do nauki w szkole. Celem zawartych w ksi±¿ce zadañ jest doskonalenie intelektualnej dojrza³o¶ci do uczenia siê matematyki. Zaproponowane æwiczenia rozwijaj± procesy poznawcze: pamiêæ, my¶lenie, spostrzegawczo¶æ, wyobra¼niê, uwagê. Zadania skonstruowane s± z my¶l± o ci±g³ym rozwijaniu aktywno¶ci twórczej dziecka oraz stymulowaniu koordynacji wzrokowo-ruchowej.<br /><br />|n|Ksi±¿ka przenosi dziecko w ¶wiat fauny zamieszkuj±cej wszystkie kontynenty ¶wiata. W ka¿dym æwiczeniu dziecko poznaje charakterystyczne gatunki zwierz±t oraz ich ubarwienie oznaczone kolorowymi plamami. W prawym górnym rogu kart wprowadzaj±cych nowe zwierzêta znajduje siê mapa konturowa z zaznaczonym obszarem wystêpowania przedstawionych gatunków. Rysunki wszystkich zwierz±t zaopatrzone s± w etykietê zawieraj±c± nazwê, dziêki czemu dziecko utrwala litery i doskonali czytanie.<br /><br />|n|Zachêcamy do obejrzenia prezentacji ksi±¿ki Ma³gorzaty Sroki w dziale <a style="font-size: 12px;font-weight: bold;color: #666666;background: url('../../_images/layout/pictograms/anchor.gif') 0px 50% no-repeat;" href="http://www.ppiw.com.pl/__test__/index.php?go=zaprezentuj_sie&sub1=ms01#">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Zaprezentuj siê</a>.$
95$Papierowe sk³adanki &#8211; laurki do samodzielnego wykonania. Zbiór oryginalnych pomys³ów na okoliczno¶ciowy prezent. Zbiorek uzupe³niaj± wiersze, które w laurce sprawi±, ¿e na niejednym obliczu zawita u¶miech.$
73$Przewodnik dla nauczyciela zawiera tre¶ci kszta³cenia uporz±dkowane w blokach tematycznych, z podzia³em na dni pracy oraz ciekawe propozycje dzia³añ edukacyjnych. Wskazuje ¶rodki dydaktyczne potrzebne danego dnia. Proponuje ró¿ne formy aktywno¶ci ucznia. Zawiera spis umiejêtno¶ci, u³atwiaj±cy przeprowadzenie bilansu osi±gniêæ ucznia, szczegó³owe opisy konkretnych rozwi±zañ metodycznych, a tak¿e zapisy w dzienniku.$
74$Przewodnik dla nauczyciela zawiera tre¶ci kszta³cenia uporz±dkowane w blokach tematycznych, z podzia³em na dni pracy oraz ciekawe propozycje dzia³añ edukacyjnych. Wskazuje ¶rodki dydaktyczne potrzebne danego dnia. Proponuje ró¿ne formy aktywno¶ci ucznia. Zawiera spis umiejêtno¶ci, u³atwiaj±cy przeprowadzenie bilansu osi±gniêæ ucznia, szczegó³owe opisy konkretnych rozwi±zañ metodycznych, a tak¿e zapisy w dzienniku.$
38$Zbiór æwiczeñ dodatkowych przeznaczonych dla dzieci rozpoczynaj±cych naukê pisania.|n|<br /><br />|n|Mog± byæ równie¿ pomoc± dla uczniów, którzy z ró¿nych przyczyn maj± trudno¶ci na pocz±tkowym etapie nauki. W ksi±¿ce znajduj± siê æwiczenia doskonal±ce spostrzeganie, koordynacjê oko-rêka, analizê i syntezê wzrokow± oraz pisanie liter, wyrazów i zdañ.$
23$W Przewodnikach dla nauczyciela znajduj± siê propozycje dzia³añ, które stanowi± podstawê planowania codziennej pracy.$
24$W Przewodnikach dla nauczyciela znajduj± siê propozycje dzia³añ, które stanowi± podstawê planowania codziennej pracy.$
34$Teksty do czytania w Czytankach to &#8211; wzbogacone ilustracjami &#8211; teksty literackie i pamiêtnik Franka. Jego szkolne do¶wiadczenia zachêcaj± uczniów do udzia³u w podobnych sytuacjach, odtwarzanych lub tworzonych na wzór abecelków &#8211; dzieciêcych bohaterów pakietu, rozbudzaj± ciekawo¶æ i zainteresowania.$
35$Teksty do czytania w Czytankach to &#8211; wzbogacone ilustracjami &#8211; teksty literackie i pamiêtnik Franka. Jego szkolne do¶wiadczenia zachêcaj± uczniów do udzia³u w podobnych sytuacjach, odtwarzanych lub tworzonych na wzór abecelków &#8211; dzieciêcych bohaterów pakietu, rozbudzaj± ciekawo¶æ i zainteresowania.$
3$Koncepcja Programu dla klasy 0 nawi±zuje do za³o¿eñ kszta³cenia zintegrowanego, w którym wiêksze znaczenie przywi±zuje siê do sposobu poznawania ni¿ do opanowania zasobów wiedzy. Proces edukacji ma tu charakter naturalny, odwo³uje siê do osobistych do¶wiadczeñ dzieci, odpowiada ich indywidualnym mo¿liwo¶ciom. Uczniowie poznaj± ¶wiat w jego harmonijnej ca³o¶ci, poprzez dzia³anie, organizowanie i przetwarzanie zdobytych informacji. G³ówny nacisk po³o¿ony jest na aktywno¶æ dzieci, tak aby dzia³ania podejmowane wspólnie i indywidualnie s³u¿y³y ich wzajemnemu wzbogacaniu.|n|<br /><br />|n|Niezwykle istotnym aspektem tak zorganizowanego procesu edukacyjnego jest odwo³ywanie siê do wewnêtrznej motywacji dzieci zwi±zanej z pasj±, ciekawo¶ci±, zdziwieniem, chêci± poznania, rado¶ci± odkrywania nowych obszarów wiedzy o ¶wiecie.$
30$Karty pracy stanowi± ciekaw± propozycjê zró¿nicowanych pod wzglêdem formy zadañ edukacyjnych dotycz±cych czytania, pisania, liczenia, wycinania, sklejania itd. Sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
33$Wiêkszo¶æ zadañ w Æwiczeniach jest przeznaczona do pracy samodzielnej. Pozwalaj± na daleko id±c± indywidualizacjê pracy, umo¿liwiaj± uczniom decydowanie o wyborze rodzaju aktywno¶ci zale¿nie od interpretacji zadania, sposobu rozwi±zania, potrzebnych materia³ów i narzêdzi.$
54$Teksty do czytania w Czytankach to &#8211; wzbogacone ilustracjami &#8211; teksty literackie i pamiêtnik Doroty. Jej szkolne do¶wiadczenia zachêcaj± uczniów do udzia³u w podobnych sytuacjach, odtwarzanych lub tworzonych na wzór abecelków &#8211; dzieciêcych bohaterów pakietu, rozbudzaj± ciekawo¶æ i zainteresowania.$
55$Teksty do czytania w Czytankach to &#8211; wzbogacone ilustracjami &#8211; teksty literackie i pamiêtnik Doroty. Jej szkolne do¶wiadczenia zachêcaj± uczniów do udzia³u w podobnych sytuacjach, odtwarzanych lub tworzonych na wzór abecelków &#8211; dzieciêcych bohaterów pakietu, rozbudzaj± ciekawo¶æ i zainteresowania.$
49$Karty pracy stanowi± ciekaw± propozycjê zró¿nicowanych pod wzglêdem formy zadañ edukacyjnych dotycz±cych czytania, pisania, liczenia, wycinania, sklejania itd. Sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
48$Karty pracy stanowi± ciekaw± propozycjê zró¿nicowanych pod wzglêdem formy zadañ edukacyjnych dotycz±cych czytania, pisania, liczenia, wycinania, sklejania itd. Sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
50$Wiêkszo¶æ zadañ w Æwiczeniach jest przeznaczona do pracy samodzielnej. Pozwalaj± na daleko id±c± indywidualizacjê pracy, umo¿liwiaj± uczniom decydowanie o wyborze rodzaju aktywno¶ci zale¿nie od interpretacji zadania, sposobu rozwi±zania, potrzebnych materia³ów i narzêdzi.$
51$Wiêkszo¶æ zadañ w Æwiczeniach jest przeznaczona do pracy samodzielnej. Pozwalaj± na daleko id±c± indywidualizacjê pracy, umo¿liwiaj± uczniom decydowanie o wyborze rodzaju aktywno¶ci zale¿nie od interpretacji zadania, sposobu rozwi±zania, potrzebnych materia³ów i narzêdzi.$
52$Wiêkszo¶æ zadañ w Æwiczeniach jest przeznaczona do pracy samodzielnej. Pozwalaj± na daleko id±c± indywidualizacjê pracy, umo¿liwiaj± uczniom decydowanie o wyborze rodzaju aktywno¶ci zale¿nie od interpretacji zadania, sposobu rozwi±zania, potrzebnych materia³ów i narzêdzi.$
53$Wiêkszo¶æ zadañ w Æwiczeniach jest przeznaczona do pracy samodzielnej. Pozwalaj± na daleko id±c± indywidualizacjê pracy, umo¿liwiaj± uczniom decydowanie o wyborze rodzaju aktywno¶ci zale¿nie od interpretacji zadania, sposobu rozwi±zania, potrzebnych materia³ów i narzêdzi.$
64$W Podrêczniku Olka znajduje siê prezentacja tematu dnia i tre¶ci kszta³cenia. Dzieci odnajd± w nim wiele wiadomo¶ci, ciekawostek i zadañ wyzwalaj±cych spontaniczno¶æ i chêæ dzia³ania.$
65$W Podrêczniku Olka znajduje siê prezentacja tematu dnia i tre¶ci kszta³cenia. Dzieci odnajd± w nim wiele wiadomo¶ci, ciekawostek i zadañ wyzwalaj±cych spontaniczno¶æ i chêæ dzia³ania.$
70$Teksty do czytania w Wypisach to &#8211; wzbogacone ilustracjami &#8211; ciekawe teksty literackie prozatorskie i poetyckie, odpowiadaj±ce tematyce poszczególnych dni pracy.$
71$Teksty do czytania w Wypisach to &#8211; wzbogacone ilustracjami &#8211; ciekawe teksty literackie prozatorskie i poetyckie, odpowiadaj±ce tematyce poszczególnych dni pracy.$
67$Karty pracy stanowi± ciekaw± propozycjê zró¿nicowanych pod wzglêdem formy zadañ edukacyjnych dotycz±cych czytania, pisania, liczenia, wycinania, sklejania itd. Sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
68$Karty pracy stanowi± ciekaw± propozycjê zró¿nicowanych pod wzglêdem formy zadañ edukacyjnych dotycz±cych czytania, pisania, liczenia, wycinania, sklejania itd. Sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
69$Karty pracy stanowi± ciekaw± propozycjê zró¿nicowanych pod wzglêdem formy zadañ edukacyjnych dotycz±cych czytania, pisania, liczenia, wycinania, sklejania itd. Sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
97$Karty pracy stanowi± ciekaw± propozycjê zró¿nicowanych pod wzglêdem formy zadañ edukacyjnych dotycz±cych czytania, pisania, liczenia, wycinania, sklejania itd. Sprzyjaj± indywidualizacji pracy dziecka, pozwalaj± na w³asn± interpretacjê zadañ, zachêcaj± do podejmowania twórczych dzia³añ, u³atwiaj± powtarzanie wiadomo¶ci i ich porz±dkowanie.$
